# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sw-RXNzYPQTFcV-xXsrjKjI3FgzEvvQ4
"""

# Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, RocCurveDisplay
import joblib

# Cargar el dataset

df = pd.read_csv("bank_marketing.csv")
print(' Dataset cargado ')
print("Dimensiones:", df.shape)
df.head()

# Análisis exploratorio
print("\nInformación del dataset:")
print(df.info())

print("\nValores nulos por columna:")
print(df.isnull().sum())

print("\nDistribución de la variable objetivo:")
print(df["y"].value_counts())

sns.countplot(x="y", data=df)
plt.title("Distribución de la variable objetivo")
plt.show()
# cuántos casos hay de cada clase en la variable Y

# variables categóricas
le = LabelEncoder()
for col in df.select_dtypes(include=["object"]).columns:
    df[col] = le.fit_transform(df[col])
 # Convierte las palabras (texto) en números, porque el modelo solo entiende valores numéricos

# Separar variables
X = df.drop("y", axis=1)
y = df["y"]

# Dividir en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print("\nTamaños de los conjuntos:")
print("Entrenamiento:", X_train.shape)
print("Prueba:", X_test.shape)

# Entrenamiento del modelo

modelo = RandomForestClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Predicciones
y_pred = modelo.predict(X_test)

# Evaluación del modelo

print("\nEvaluación del modelo")
print("Accuracy:", round(accuracy_score(y_test, y_pred), 3))
print("ROC AUC:", round(roc_auc_score(y_test, modelo.predict_proba(X_test)[:, 1]), 3))

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

# Matriz de confusión
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Greens")
plt.title("Matriz de confusión")
plt.xlabel("Predicción")
plt.ylabel("Valor real")
plt.show()

# Curva ROC
RocCurveDisplay.from_estimator(modelo, X_test, y_test)
plt.title("Curva ROC del modelo")
plt.show()
# Es una métrica de evaluación del modelo, llamada Área bajo la curva ROC.
# Sirve para medir qué tan bien distingue el modelo entre las clases (por ejemplo, “sí” y “no”)

# Importancia de variables y guardar

importancias = pd.Series(modelo.feature_importances_, index=X.columns)
importancias = importancias.sort_values(ascending=False)

print("\nVariables más importantes:")
print(importancias.head(10))

importancias.head(10).plot(kind="barh", color="skyblue")
plt.title("Importancia de las variables (Top 10)")
plt.xlabel("Importancia")
plt.show()
# muestra qué variables fueron más importantes para el modelo Random Forest al hacer sus decisiones


joblib.dump(modelo, "modelo_random_forest")
# Guarda el modelo entrenado en un archivo